[Rainmeter]
Update=#UpdateMs#
AccurateText=1
DynamicWindowSize=1
@include=#@#Variables.inc
@include2=#@#Styles.inc

[MeasureGPUClock]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUClock#

[MeasureGPUUtil]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUUtil#
MinValue=0
MaxValue=100

[MeasureGPUTemp]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUTemp#

[MeterBg]
Meter=Shape
MeterStyle=StyleBg

[MeterTitle]
Meter=String
MeterStyle=StyleTitle
Text=GPU

[Divider]
Meter=Image
MeterStyle=StyleDivider
X=#DividerX#
Y=#DividerY#

; -------------------------
; Clock
; -------------------------

[LabelClock]
Meter=String
MeterStyle=StyleLabel
Y=(#LineH#*2)
Text=Clock

[ValueClock]
Meter=String
MeterStyle=StyleValue
MeasureName=MeasureGPUClock
Y=(#LineH#*2)
Text=%1 MHz

; -------------------------
; Utilization
; -------------------------

[LabelUtil]
Meter=String
MeterStyle=StyleLabel
Y=(#LineH#*3)
Text=Utilization

[ValueUtil]
Meter=String
MeterStyle=StyleValue
MeasureName=MeasureGPUUtil
Y=(#LineH#*3)
Text=%1%

[BarUtilBg]
Meter=Image
MeterStyle=StyleBarBg
Y=((#LineH#*3)+#BarOffsetY#)

[BarUtil]
Meter=Bar
MeasureName=MeasureGPUUtil
MeterStyle=StyleBar
Y=((#LineH#*3)+#BarOffsetY#)

; -------------------------
; Temperature
; -------------------------

[LabelTemp]
Meter=String
MeterStyle=StyleLabel
Y=(#LineH#*4)
Text=Temperature

[ValueTemp]
Meter=String
MeterStyle=StyleValue
MeasureName=MeasureGPUTemp
Y=(#LineH#*4)
Text=%1 [\x00B0]C

; -------------------------
; GPU utilization graph
; -------------------------

[GraphUtilBg]
Meter=Shape
Shape=Rectangle #GraphX#,#GraphY#,#GraphW#,#GraphH#,#GraphRadius# | Fill Color #ColorGraphBg# | StrokeWidth 1 | Stroke Color #ColorBorder#

[GraphUtil]
Meter=Line
MeasureName=MeasureGPUUtil
MeterStyle=StyleGraphLine
Y=#GraphY#
LineCount=1
LineColor=#ColorGraph1#
