[Rainmeter]
Update=#UpdateMs#
AccurateText=1
DynamicWindowSize=1
@include=#@#Variables.inc
@include2=#@#Styles.inc

[MeasureGPUClock]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUClock#

[MeasureGPUUtil]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUUtil#
MinValue=0
MaxValue=100

[MeasureVRAMPercent]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUVRAMPercent#
MinValue=0
MaxValue=100

[MeasureVRAMUsed]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUVRAMUsed#

[MeasureVRAMFree]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUVRAMFree#

[MeasureVRAMTotal]
Measure=Calc
Formula=MeasureVRAMUsed + MeasureVRAMFree
DynamicVariables=1

[MeterBg]
Meter=Shape
MeterStyle=StyleBg

[MeterTitle]
Meter=String
MeterStyle=StyleTitle
Text=GPU

[Divider]
Meter=Image
MeterStyle=StyleDivider
X=#DividerX#
Y=#DividerY#

; -------------------------
; Clock
; -------------------------

[LabelClock]
Meter=String
MeterStyle=StyleLabel
Y=(#LineH#*2)
Text=Clock

[ValueClock]
Meter=String
MeterStyle=StyleValue
MeasureName=MeasureGPUClock
Y=(#LineH#*2)
Text=%1 MHz

; -------------------------
; Utilization
; -------------------------

[LabelUtil]
Meter=String
MeterStyle=StyleLabel
Y=(#LineH#*3)
Text=Utilization

[ValueUtil]
Meter=String
MeterStyle=StyleValue
MeasureName=MeasureGPUUtil
Y=(#LineH#*3)
Text=%1%

[BarUtilBg]
Meter=Image
MeterStyle=StyleBarBg
Y=((#LineH#*3)+#BarOffsetY#)

[BarUtil]
Meter=Bar
MeasureName=MeasureGPUUtil
MeterStyle=StyleBar
Y=((#LineH#*3)+#BarOffsetY#)

; -------------------------
; VRAM
; -------------------------

[LabelVRAM]
Meter=String
MeterStyle=StyleLabel
Y=(#LineH#*4)
Text=VRAM

[ValueVRAM]
Meter=String
MeterStyle=StyleValue
MeasureName=MeasureVRAMUsed
MeasureName2=MeasureVRAMTotal
Y=(#LineH#*4)
Text=%1 / %2 MB

[BarVRAMBg]
Meter=Image
MeterStyle=StyleBarBg
Y=((#LineH#*4)+#BarOffsetY#)

[BarVRAM]
Meter=Bar
MeasureName=MeasureVRAMPercent
MeterStyle=StyleBar
Y=((#LineH#*4)+#BarOffsetY#)

; -------------------------
; VRAM graph
; -------------------------

[GraphVRAMBg]
Meter=Shape
Shape=Rectangle #GraphX#,#GraphY#,#GraphW#,#GraphH#,#GraphRadius# | Fill Color #ColorGraphBg# | StrokeWidth 1 | Stroke Color #ColorBorder#

[GraphVRAM]
Meter=Line
MeasureName=MeasureVRAMPercent
MeterStyle=StyleGraphLine
Y=#GraphY#
LineCount=1
LineColor=#ColorGraph1#
