[Rainmeter]
Update=#UpdateMs#
AccurateText=1
DynamicWindowSize=1
@include=#@#Variables.inc
@include2=#@#Styles.inc

[MeasureVRAMPercent]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUVRAMPercent#
MinValue=0
MaxValue=100

[MeasureVRAMUsed]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUVRAMUsed#

[MeasureVRAMFree]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=#AIDAKey#
RegValue=#AIDA_GPUVRAMFree#

[MeasureVRAMTotal]
Measure=Calc
Formula=MeasureVRAMUsed + MeasureVRAMFree
DynamicVariables=1

[MeterBg]
Meter=Shape
MeterStyle=StyleBg

[MeterTitle]
Meter=String
MeterStyle=StyleTitle
Text=VRAM

[Divider]
Meter=Image
MeterStyle=StyleDivider
X=#DividerX#
Y=#DividerY#

; -------------------------
; Usage
; -------------------------

[LabelVRAM]
Meter=String
MeterStyle=StyleLabel
Y=(#LineH#*2)
Text=Usage

[ValueVRAM]
Meter=String
MeterStyle=StyleValue
MeasureName=MeasureVRAMUsed
MeasureName2=MeasureVRAMTotal
Y=(#LineH#*2)
Text=%1 / %2 MB

[BarVRAMBg]
Meter=Image
MeterStyle=StyleBarBg
Y=((#LineH#*2)+#BarOffsetY#)

[BarVRAM]
Meter=Bar
MeasureName=MeasureVRAMPercent
MeterStyle=StyleBar
Y=((#LineH#*2)+#BarOffsetY#)

; -------------------------
; VRAM graph (0–100 %)
; -------------------------

[GraphVRAMBg]
Meter=Shape
Shape=Rectangle #GraphX#,#GraphY#,#GraphW#,#GraphH#,#GraphRadius# | Fill Color #ColorGraphBg# | StrokeWidth 1 | Stroke Color #ColorBorder#

[GraphVRAM]
Meter=Line
MeasureName=MeasureVRAMPercent
MeterStyle=StyleGraphLine
Y=#GraphY#
LineCount=1
LineColor=#ColorGraph1#
